### ISSUE TITLE
Replace unicorn on buy, sell, and redeem.

### ISSUE THREAD

**Issue by jordanmack** [hidotmatrix/nervos-unisocks-clone-V2#10]
Replace the left top unicorn emoji with a small durag image. If the durag image doesn't look right at that size let's just remove it for now.

![20220622130426](https://user-images.githubusercontent.com/37931/175126870-569f5c8c-007e-4c85-9537-2483d1786260.png)

**Comment by Mohsinsiddi** [comment]
![Screenshot from 2022-06-27 23-07-18](https://user-images.githubusercontent.com/47236913/176001968-7ba8019e-b2d0-4557-a62a-ca9c8c5c7898.png)
![Screenshot from 2022-06-27 23-07-25](https://user-images.githubusercontent.com/47236913/176001976-086e843a-07a6-41ee-9e1d-62f59ea7ddc3.png)
As unisocks have use Unicorn symbols instead of logo image, it is tough to change logo for this
Can we create custom aria-label for our project like they did

Earlier Snippet
          <span role="img" aria-label="unicorn">
             🦄 
          </span>{' '}
          Unicorn>

Current Snippet
          <span role="img" aria-label="unicorn">
            {/* 🦄 */}
            <img src={logo} width="100%" height="30" alt=""></img>
          </span>{' '}
          Addig snippet for ref

**Comment by jordanmack** [comment]
The logo should not have a text label. Attaching two PNG files with the label removed.

This has the standard dark background.
![durag-small-dark](https://user-images.githubusercontent.com/37931/176063344-c36b24d5-7efe-4fce-b407-f58344171be3.png)

This has the background removed, but there is a dark outline. It still should look fine on dark backgrounds.
![durag-small-transparent](https://user-images.githubusercontent.com/37931/176063346-1a808d4b-35d9-4746-ad57-761d24f6c117.png)

If you need an Aria text replacement it would be "Durag". If there is something else you're trying to describe I don't think I understand.

**Comment by jordanmack** [comment]
@Mohsinsiddi  If neither one of the provided durag icons looks right on the buy, sell, and redeem pages, just remove it entirely. It's not essential.

**Comment by Mohsinsiddi** [comment]
![Screenshot from 2022-06-28 17-13-12](https://user-images.githubusercontent.com/47236913/176170364-9391dbc7-5002-4bf4-96fe-6ff6b9c31ec0.png)
![Screenshot from 2022-06-28 17-13-16](https://user-images.githubusercontent.com/47236913/176170372-4af69e44-3272-4d99-8116-1a8eb1d1542b.png)

Remove the Unicorn Icon
