### ISSUE TITLE
Remove unicorn from learn more screen.

### ISSUE THREAD

**Issue by jordanmack** [hidotmatrix/nervos-unisocks-clone-V2#11]
From the front page, click learn more and you should see the unicorn in the top left corner.

![20220627172353](https://user-images.githubusercontent.com/37931/176064885-9f2a57a9-8724-4bd2-b4f1-d455a7d2a163.png)

**Comment by Mohsinsiddi** [comment]
![Screenshot from 2022-06-28 17-26-25](https://user-images.githubusercontent.com/47236913/176172610-79258525-8f01-4a8f-bb00-15e9b8ac187b.png)

Removed
