### ISSUE TITLE
Replace favicon

### ISSUE THREAD

**Issue by jordanmack** [hidotmatrix/nervos-unisocks-clone-V2#12]
Replace the favicon with the following image.

![durag-small-dark](https://user-images.githubusercontent.com/37931/176065039-6d49606f-392c-473d-a891-6ef768c14f51.png)

**Comment by Mohsinsiddi** [comment]
![Screenshot from 2022-06-28 17-25-14](https://user-images.githubusercontent.com/47236913/176172449-58a3c360-8115-4565-93a8-fa72401853f1.png)

Changed Favicon
