### ISSUE TITLE
Make scrollbars automatic rather than always visible.

### ISSUE THREAD

**Issue by jordanmack** [hidotmatrix/nervos-unisocks-clone-V2#13]
On the right side and bottom side there are scrollbars that are always visible and this doesn't look good. I checked and the overflow property is set to `scroll`, which can easily be set to `auto` to fix it.

![20220705213929](https://user-images.githubusercontent.com/37931/177469614-2e786a76-5b45-40a3-af68-e208647eff18.png)

**Comment by Mohsinsiddi** [comment]
This has been fixed!
