### ISSUE TITLE
Remove emojis from stats page.

### ISSUE THREAD

**Issue by jordanmack** [hidotmatrix/nervos-unisocks-clone-V2#2]
![20220622124055](https://user-images.githubusercontent.com/37931/175122432-17b42493-d6d4-491b-88bb-c382dc8938a1.png)

It appears they are using a sock emoji. To make it simple, let's just remove all three emoji for now.

**Comment by Mohsinsiddi** [comment]
![Screenshot from 2022-06-27 22-16-53](https://user-images.githubusercontent.com/47236913/175993394-db34a3cb-7ece-4ec9-b70b-b836e1272568.png)

We removed emojis for now
