### ISSUE TITLE
Update site colors.

### ISSUE THREAD

**Issue by jordanmack** [hidotmatrix/nervos-unisocks-clone-V2#3]
Current screenshot.
![20220622124235](https://user-images.githubusercontent.com/37931/175122655-6728ccaa-ce2d-4537-b078-3f2154b4645f.png)

Color instructions - use judgement to implement appropriately.
![20220622124412](https://user-images.githubusercontent.com/37931/175122907-d1996421-b143-4b8a-a5b6-1e303ab61a9c.png)

Logo image for color reference.
![photo_2022-06-14_00-18-49](https://user-images.githubusercontent.com/37931/175122914-bf1f7204-9e38-46f4-9890-f38daf3f8a97.jpg)

**Comment by Mohsinsiddi** [comment]
![Screenshot from 2022-06-27 22-45-32](https://user-images.githubusercontent.com/47236913/175998345-6df5a929-592d-4e2e-b8ab-2e8e1b41c479.png)
Updated logo and theme color

**Comment by jordanmack** [comment]
Problem on this page. https://unisocks-nervos.netlify.app/status

Changing text color to white should fix.

![20220627180009](https://user-images.githubusercontent.com/37931/176064488-6ac26952-9669-4ad4-a052-6a903284f53f.png)

**Comment by jordanmack** [comment]
Links and buttons are still pink. They should be changed to the blue color. #136de7

![20220627180213](https://user-images.githubusercontent.com/37931/176064731-068bf848-515c-487b-9d3f-7815efd3d75d.png)

**Comment by Mohsinsiddi** [comment]
Done with the changes!

**Comment by jordanmack** [comment]
@Mohsinsiddi Still a few piece of text on the order page under the button that are black font on black background.

![20220706220224](https://user-images.githubusercontent.com/37931/177695430-ea2cb9c0-9b79-4c01-9382-6f5f4c50e336.png)

**Comment by Mohsinsiddi** [comment]
Updated colors from black to white now
