### ISSUE TITLE
Replace logo in left corner.

### ISSUE THREAD

**Issue by jordanmack** [hidotmatrix/nervos-unisocks-clone-V2#4]
![20220622124235](https://user-images.githubusercontent.com/37931/175123318-412fac59-6a1c-46ca-a483-715e7d06ebd7.png)
![photo_2022-06-14_00-18-49](https://user-images.githubusercontent.com/37931/175123332-54066a09-5932-41ac-91ae-113b7d406f16.jpg)

**Comment by Mohsinsiddi** [comment]
![Screenshot from 2022-06-27 22-45-32](https://user-images.githubusercontent.com/47236913/175998430-d2d95c10-4b33-45c7-b919-4cbdc51513eb.png)
Replaced logo
