### ISSUE TITLE
Questions on the setup instructions.

### ISSUE THREAD

**Issue by jordanmack** [hidotmatrix/nervos-unisocks-clone-V2#5]
Questions on the setup instructions:

> FAUNADB_SERVER_SECRET=

Where/how is this generated?

> REACT_APP_SITE_RECAPTCHA_KEY=

Is this the site key? Does it also need the secret key somewhere?

**Comment by Mohsinsiddi** [comment]
I will soon create a demo video , how create keys and also how to configure the collections and indexes for our project

**Comment by Mohsinsiddi** [comment]
Hi
Here's the dmo video link
https://www.loom.com/share/edd028f122eb41c496f0ef357e7444fb
