### ISSUE TITLE
Limit buying options to just CKB.

### ISSUE THREAD

**Issue by jordanmack** [hidotmatrix/nervos-unisocks-clone-V2#9]
To make this simple, limit buying options to just CKB for now. (CKB/pCKB is the main token on Godwoken.)
![20220622130158](https://user-images.githubusercontent.com/37931/175126427-5213960d-2bdf-4135-87b3-e595041bf9bb.png)

**Comment by Mohsinsiddi** [comment]
We need a stable coin option here as the entire project is showing price based on comparing with USD pegged stable coin
I will need some time here to figure it and update it if needed to do so

**Comment by Mohsinsiddi** [comment]
![Screenshot from 2022-06-27 23-16-31](https://user-images.githubusercontent.com/47236913/176003625-2d66452d-507b-467e-9b2d-3513cea3d65e.png)
ETH is being used most places!
But it is doable need time for it

**Comment by Mohsinsiddi** [comment]
![Screenshot from 2022-06-27 23-18-31](https://user-images.githubusercontent.com/47236913/176004021-a1310117-c5b2-474b-8ace-025d18ab2bcf.png)
![Screenshot from 2022-06-27 23-18-34](https://user-images.githubusercontent.com/47236913/176004026-b36a5ffb-3149-4490-8a64-1f180c5a2431.png)

Changed ETH to CKB

**Comment by jordanmack** [comment]
@Mohsinsiddi If the stable coin is absolutely required, then this issue can be closed.
